import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="navbar"> 
      <Link href="/" className="logo">오늘 뭐 먹지?</Link> 
      <Link href="/list">게시판</Link> 
      </div>  
        {children}
        </body>
    </html>
  )
}
